package paymentsUI;

import java.util.Random;

public class PaymentUI_CommonUtilities {

	protected static String creditOrDebitCardPageTextxpath= "//p[text()='#']";
	public static String creditCardPageText= "Enter your credit card details.";
	public static String debitCardPageText= "Enter your debit card details.";
	protected static String convenienceTextxpath= "//p[contains(text(),'#')]";
	
	public static String convenienceFeeText= "Convenience fee";
	protected static String cardNumberxpath= "//input[contains(@id,'cardNumber')]";
	protected static String expiryMonthxpath = "//select[contains(@id,'expiryMonth')]";
	protected static String expiryYearxpath = "//select[contains(@id,'expiryYear')]";
	protected static String cardHolderNamexpath = "//input[contains(@id,'name')]";
	protected static String cvvNumberxpath = "//input[contains(@id,'cvv')]";
	
	protected static String ewCardNumberXpath= "//input[contains(@id,'CC')]";
	protected static String ewCardExpiryMonthXpath = "//select[contains(@id,'CcExpirationMonth')]";
	protected static String ewCardExpiryYearXpath = "//select[contains(@id,'CcExpirationYear')]";
	protected static String ewCardHolderNameXpath = "//input[contains(@name,'name')]";
	protected static String ewAddCardButtonXpath = "//button[contains(@id,'addCard')]";
	public static String ewAddCardValidExpiryMonth= "5";
	public static String ewAddCardValidExpiryYear= "2021";
	public static String ewAddCardStreetAddrXpath= "//textarea[contains(@id,'xpress_street_address')]";
	public static String ewAddCardCityXpath= "//input[contains(@id,'xpress_city')]";
	public static String ewAddCardStateXpath= "//input[contains(@id,'xpress_state')]";
	public static String ewAddCardPinCodeXpath= "//input[contains(@id,'xpress_pin')]";
	public static String ewAddCardCountryXpath= "//input[contains(@id,'xpress_country')]";
	public static String ewAddCardAddrButtonXpath= "//button[contains(@id,'saveBillAddress')]";
	
	protected static String cardNumbererrorxpath = "//input[contains(@id,'cardNumber')]/../../../following-sibling::p[text()='errortext']";
	protected static String cardHoldererrorxpath= "//input[contains(@id,'name')]/../../following-sibling::p[text()='errortext']";
	protected static String cardCvverrorxpath= "//input[contains(@id,'cvv')]/../../../../following-sibling::p[text()='errortext']";
	protected static String expiryerrorxpath= "//select[contains(@id,'expiryMonth')]/../../../../../following-sibling::div/p[text()='errortext']";
	protected static String errortextCardNumber= "Please enter a valid card number";
	protected static String errortextExpiryMonth= "Please enter a valid expiry month";
	protected static String errortextExpiryYear= "Please enter a valid expiry year";
	protected static String errortextCardHolderName= "Please enter a valid name";
	protected static String errortextCvv= "Please enter a valid cvv";
	public static String errortextCvvXpath= "//p[text()='Please enter a valid cvv']";
	public static String makePaymentbutton= "//button[text()='Make Payment']";
	protected static String debitCardPaymentxpath= "//p[text()='Debit card']";
	protected static String creditCardPaymentxpath= "//p[text()='Credit card']";
	protected static String netBankingPaymentxpath= "//p[text()='Net banking']";
	protected static String nbHDFCSelectXpath = "//ul[@class='Datalist radioList radio-item-list bt-0 bb-0 ']/li[2]";
	protected static String nbCitiSelectXpath = "//ul[@class='Datalist radioList radio-item-list bt-0 bb-0 ']/li[5]";
	protected static String phonePeMobileNo="//input[@name='mobileNumber']";
	protected static String phonePeMobileNoSubmit= "//button[@id='onboardingFormSubmitBtn']";
	protected static String footerxpath= "//a[text()='footername']";
	protected static String footerOne= "About Us";
	protected static String footerTwo= "Careers";
	protected static String footerThree= "FAQs";
	protected static String footerFour= "Support";
	protected static String footerFive= "Blog";
	protected static String footerSix= "Mobile";
	protected static String footerSeven= "Cleartrip for Business";
	protected static String footerEight= "Gift Cards";
	protected static String footerNine= "Referral Program";
	protected static String footerTen= "Holiday Planner";
	protected static String sectionTripDetails= "Trip Details";
	protected static String sectionTravellers= "Travellers";
	protected static String sectionTravellersXpath= "//p[contains(text(),'Travellers')]";
	protected static String sectionItinerary=  "Itinerary";
	protected static String sectionItineraryXpath=  "//p[contains(text(),'Itinerary')]";
	protected static String sectionPricingDetails= "Pricing Details";
	protected static String sectionPricingDetailsXpath= "Pricing Details";
	protected static String sectionxpath= "//p[text()='sectionname']";
	protected static String triptravelleranditinerarysectionfieldxpath= "//span[text()='sectionfieldname']";
	protected static String pricingsectionfieldxpath= "//p[text()='pricingsectionfieldname']";
	protected static String recaptchaxpath= "//label[contains(@id,'recaptcha')]";
	protected static String triptravelleranditinerarysectionfieldTripId= "TripId";
	protected static String triptravelleranditinerarysectionfieldAdult= "Adult";
	protected static String triptravelleranditinerarysectionfieldTrain= "Train";
	protected static String triptravelleranditinerarysectionfieldTrainXpath="//p[text()='Train Itinerary']";
	protected static String triptravelleranditinerarysectionfieldDeparture= "Departs";
	protected static String triptravelleranditinerarysectionfieldArrival= "Arrives";
	protected static String triptravelleranditinerarysectionfieldClass= "Class";
	protected static String triptravelleranditinerarysectionfieldQuota= "Quota";
	protected static String triptravelleranditinerarysectionfieldUpdatedAvailability= "Updated Availability";
	protected static String showFareBreakUp="//p[contains(text(),'Show fare break up')]";
	protected static String pricingsectionfieldOtherRailwayCharges= "Other Railway Charges";
	protected static String pricingsectionfieldAgentServiceCharges= "Agent Service Charge (Inclusive of GST)";
	protected static String pricingsectionfieldGST= "(Inclusive of GST)";
	protected static String pricingsectionfieldConvenienceFee= "Convenience fee";
	protected static String pricingsectionfieldInuranceCharge= "Insurance Charges";
	protected static String pricingsectionfieldRefundType= "Refund Type";
	public static String validCardNumber= "5123456789012346";
	public static String validExpiryMonth= "May (05)";
	public static String validExpiryYear= "2020";
	public static String validCvv= "123";
	public static String validCardName= "Tester Test";
	public static String invalidCardNumber= "5123456789012345";
	public static String validAmexCardNumber= "345678000000007";
	public static String validAmexExpiryYear= "2021";
	public static String invalidAmexExpiryYear= "2020";
	public static String validAmexCvv= "1234";
	public static String invalidAmexCvv= "4321";
	protected static String paymentModexpath= "//p[text()='paymentmode']";
	protected static String paymentModeCC= "Credit card";
	protected static String paymentModeDC= "Debit card";
	protected static String paymentModeNB= "Net banking";
	protected static String paymentModeUPI= "UPI";
	protected static String paymentModeWallet="Wallets";
	protected static String paymentModes="//ul[@id='paymentModeTab']";
	protected static String paymentModeADCB= "ADCB TouchPoints";
	protected static String paymentModeAP= "Apple Pay";
	protected static String paymentModeStoredCard= "Stored cards.";
	public static String nbOption1= "//p[text()='Please enter a valid cvv']";
	protected static String nbDropDown="//select[@name='bankId']";
	protected static String nbHdfcSubmit="//input[@name='proceed']";
	protected static String nbCitiSubmit="//input[@value='Return To the Merchant Site']";
	protected static String nbHdfcCancel="//input[@name='cancel']";
	public static String popularBanks="//p[text()='Popular banks']";
	public static String errortextSelectBank="Please select your bank";
	public static String errorSelectBankxpath="//p[text()='Please select your bank']";
	protected static String errorTextInvalidCCDetailsxpath= "//div[contains(@class,'retry')]";
	protected static String captchaErrorXpath= "//p[text()='captchaerrormessage']";
	public static String captchaErrorName= "Please validate captcha";
	public static String errorTextInvalidCC="Error in credentials entered. Verify your details and try again.";
	protected static String licenseAgreementxpath= "//span[contains(text(),'I understand and agree to the rules and restrictions of this fare, ')]/../label[contains(@class,'checkbox')]";
	public static String licenseAgreementErrorText= "Please accept the terms and conditions to proceed with this booking.";
	public static String invalid3DFailureXpath="//div[text()='Oops! Your payment failed. If you were charged, any amount deducted will be reversed automatically.']";
	public static String licenseAgreementErrorTextXpath= "//p[text()='Please accept the terms and conditions to proceed with this booking.']";
	protected static String licenseAgreementFieldxpath= "//a[text()='#']";
	protected static String licenseAgreementFieldBookingPolicy= "Booking policy";
	protected static String licenseAgreementFieldPrivacyPolicy= "Privacy Policy" + " ";
	protected static String licenseAgreementFieldTermsAndConditions= " "+ "Terms & Conditions" + " ";
	protected static String imagesXpath= "//a[contains(@title,'imagename')]";
	protected static String imageNameVisa= "Verified by Visa";
	protected static String imageNameMasterCard= "MasterCard SecureCode";
	protected static String imageNameAmex= "SafeKey";
	protected static String irctcLogoxpath= "//img[@class='irctcLogo']";
	protected static String totalAmountWithTaxXpath= "//span[text()='Total inclusive all taxes']";
	protected static String storedCardTextXpath= "//p[text()='Save this card and make single-click payments']";
	public static String storedCardCheckbox= "//p[text()='Save this card and make single-click payments']/../label[contains(@class,'checkbox')]";
	public static String paymentSuccessHeaderTextXpath= "//h1[text()='Payment successful!']";
	public static String paymentSuccessMessageTextXpath= "//span[text()=' to view your booking details and Trip ID.']";
	protected static String amexGatewayAuthenticationSubmitxpath= "//input[@type='submit']";
	public static String retry3DFailureHeaderXpath= "//h1[text()='Uh-oh! Something went wrong']";
	public static String retry3DFailureMessageXpath= "//span[text()='We weren't able to complete the payment. Please try again in 15-20 minutes.']";
    public static String amexGatewayAuthenticationFailureValue= "(N) Authentication Failed";
    public static String amexGatewayAuthenticationFailureXpath= "//select[contains(@id,'AuthResult')]";
    public static String paymentInProgressHeaderXpath="//h1[text()='Payment in progress']";
    public static String paymentInProgressMessageXpath= "//span[text()='The payment for this itinerary is already in progress. Please wait 20 minutes and visit your profile to verify the booking status.']";
    public static String upiErrorTextXpath= "//p[text()='Please select any UPI payment method']";
    public static String upiErrorTextSelectUPI="Please select any UPI payment method";
    public static String upiModeXpath= "//p[text()='UPI']";
    public static String walletsXpath="//p[contains(text(),'Wallets')]";
    public static String walletErrorTextSelectWallet="Please select any wallet";
    public static String walletErrorTextXpath= "//p[text()='Please select any wallet']";
    public static String walletAmazonPaySelectXpath="//ul[contains(@class,'Datalist radioList')]/li[8]";
    public static String amazonPayUsernameXpath="//input[@name='email']";
    public static String amazonPayPasswordXpath="//input[@name='password']";
    public static String amazonPaySubmitButtonXpath="//input[@id='signInSubmit']";
    public static String amazonPayOTPPageXpath="//h1[contains(text(),'Authentication required')]";
   
    public static String nbModeXpath= "//p[text()='Net banking']";
    public static String storedCardXpath= "//p[text()='Stored cards']";
    public static String storedCardNewXpath= "//p[text()='Stored Card']";
    public static String nbErrorTextXpath="//p[text()='Please select your bank']";
    public static String amexCardIsPresentEndingWithSeven= "//p[contains(text(),'Amex')]";
   
    public static String storedCardCvvBoxXpath= "//p[contains(text(),'345678')]/../following-sibling::div/div/input[@name='cvv']";
    public static String manageTripsXpath= "//a[text()='Manage trips']";
    public static String expresswayXpath= "//a[text()='Expressway']";
    public static String removeStoredCardXpath= "//a[@title='Remove this card']";
    public static String walletCheckBox= "(//label[@class='checkbox-round'])[1]";
	public static String citiBankTransaction="//select[@name='PAID']";
	public static String paymentSuccess="//h1[contains(text(),'Payment successful!')]";
	public static String convenienceXpathNew="//p[contains(text(),'Includes a convenience fee of')]";
    protected static String homePageUserAccountLinkXpath= "//a[@id='userAccountLink']";
    protected static String homePageAccountEWLinkXpath= "//a[contains(@href,'/account/expressway?src=qtct&sub_src=expressway')]";
	protected static String addNewCardEWXpath="//button[@id='startExpress']";
    
    public static int generateFiveDigitRandomNumber(){
		Random r = new Random( System.currentTimeMillis() );
		System.out.println("random Num "+r);
		return 10000 + r.nextInt(20000);
	}
	
	
}
